ci: Add configuration for GitHub Actions to master branch (#546)
* ci: Add configuration for GitHub Actions

Add basic GitHub Actions configuration based on mp11
Remove Actions jobs using GCC 4.7 and 4.8 - unsupported compilers
Run b2 with --abbreviate-paths on Windows
The -std=c++1z is broken for clang-4.0 but no need to test it
Add -mbig-obj to GCC on Windows
  - That is to avoid string table overflow and file too big
Define _GLIBCXX_USE_CXX11_ABI=0 for clang 3.5, 3.6, 3.7
  - Should help avoid linker error:
    `undefined reference to std::ios_base::failure::failure(char const*, std::error_code const&)`
Disable certain check in algorithm_channel_relation test for clang<3.8

(cherry picked from develop commit 81b4dc08bd9177bf9361194a66b0e70cfd6438e8)

* ci: Disable GA build with clang 3.5 until fix #542 is merged into master